"use client";
import localFont from "next/font/local";
import "./globals.css";
import { TonConnectUIProvider } from "@tonconnect/ui-react";
import { init, viewport, swipeBehavior } from "@telegram-apps/sdk-react";
import { useEffect } from "react";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

const manifestUrl =
  "https://rose-just-skunk-656.mypinata.cloud/ipfs/bafkreia5ycr47j5ffcyvyyxxlkiqj4nxaraejlzhfyr2tnrevv542aqdvq";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  useEffect(() => {
    const initData = async () => {
      init();

      if (swipeBehavior.mount.isAvailable()) {
        swipeBehavior.mount();
      }

      if (swipeBehavior.disableVertical.isAvailable()) {
        swipeBehavior.disableVertical();
      }

      // viewport
      if (viewport.mount.isAvailable() && !viewport.isMounting()) {
        await viewport.mount();
        // viewport.requestFullscreen();
        viewport.expand();
      }
    };
    initData();
  }, []);

  return (
    <TonConnectUIProvider manifestUrl={manifestUrl}>
      <html
        lang="en"
        className="h-full">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
          {children}
        </body>
      </html>
    </TonConnectUIProvider>
  );
}
